#!/usr/bin/env bash

code --install-extension anseki.vscode-color
code --install-extension christian-kohler.npm-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension dzannotti.vscode-babel-coloring
code --install-extension eg2.vscode-npm-script
code --install-extension t-sauer.autolinting-for-javascript
code --install-extension timothymclane.react-redux-es6-snippets
code --install-extension Zignd.html-css-class-completion
code --install-extension abusaidm.html-snippets
code --install-extension christian-kohler.path-intellisense
code --install-extension mohsen1.prettify-json
code --install-extension robinbentley.sass-indented
code --install-extension mrmlnc.vscode-scss
code --install-extension cssho.vscode-svgviewer
code --install-extension whtouche.vscode-js-console-utils
code --install-extension wix.vscode-import-cost
code --install-extension abusaidm.html-snippets
code --install-extension formulahendry.auto-rename-tag
code --install-extension hookyqr.beautify
code --install-extension formulahendry.code-runner
code --install-extension joelday.docthis
code --install-extension grapecity.gc-excelviewer
code --install-extension donjayamanne.githistory
code --install-extension knisterpeter.vscode-github
code --install-extension eamodio.gitlens
code --install-extension xabikos.javascriptsnippets
code --install-extension esbenp.prettier-vscode
code --install-extension xabikos.reactsnippets
code --install-extension rebornix.ruby
code --install-extension juanblanco.solidity
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension robertohuertasm.vscode-icons