# Load environment variables first
source ~/code/dotfiles/zsh/config/env.zsh

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load.
ZSH_THEME="robbyrussell"

# Cleaned up default oh-my-zsh comments - kept config minimal

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

plugins=(
    git
    github
    golang
    tig
)

source $ZSH/oh-my-zsh.sh

# Load additional configs
source ~/code/dotfiles/zsh/config/navigation.zsh
source ~/code/dotfiles/zsh/config/aliases.zsh

# Load asdf (Homebrew version)
. $(brew --prefix asdf)/libexec/asdf.sh
