# Add local binaries
export PATH="/usr/local/bin:$PATH"

# Add my custom commands
export PATH="$HOME/bin:$PATH"

source ~/.zplug/init.zsh

zplug 'mafredri/zsh-async', from:github
zplug 'sindresorhus/pure', use:pure.zsh, from:github, as:theme
zplug 'zsh-users/zsh-completions'
zplug 'zsh-users/zsh-autosuggestions', at:develop
zplug 'b4b4r07/enhancd', use:"init.sh"
zplug "plugins/bundler", from:oh-my-zsh
zplug "plugins/colored-man-pages", from:oh-my-zsh
zplug 'zsh-users/zsh-syntax-highlighting', defer:3

zplug load 

for zsh_source in $HOME/code/dotfiles/zsh/config/*.zsh; do
  source $zsh_source
done

if zplug check b4b4r07/enhancd; then
  export ENHANCD_FILTER=fzf-tmux
fi

. $HOME/.asdf/asdf.sh

. $HOME/.asdf/completions/asdf.bash

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
